### ISSUE TITLE
A question about implemenation of hybrid A* search

### ISSUE THREAD

**Issue by KailinTong** [KumarRobotics/conformal_lattice_planner#4]
Dear Ke,

this part is not really clear in the paper:
"To ensure reasonable runtime, hybrid-A* is applied. Longitudinal speed is discretized to three intervals, while the temporal dimension is left undiscretized."

How is the longitudinal speed discretized? what is the temporal dimension?

And could you kindly tell me which part of the code corresponding to the Hybrid A* search?

Many thanks and kind regards,
Kailin

**Comment by ke-sun** [comment]
Just to clarify, spatiotemporal lattice planner is not proposed by this work. For the actual details, it's recommend to follow the work by [M. McNaughton, et, al](https://ieeexplore.ieee.org/abstract/document/5980223?casa_token=qQo8GFNpJ9sAAAAA:BpnB1jBvvxfYk5x5aKH5RBZfPozx4ZYwFNsiGy_MduJpNMel1AW0mcgWAG5hPl6d7ZLQE5k).

An implementation of it in this repository can be found in `spatiotemporal_lattice_planner.cpp`.
As for how speed and time are discretized, please take a look at line 97-118 in `spatiotemporal_lattice_planner.h`.

**Comment by KailinTong** [comment]
Thank you for your reply.

So your Feedback Enhanced Motion Planning does not use Hybird A*. Do I understand correctly?

**Comment by ke-sun** [comment]
You are right. It is not used in the proposed work.

To avoid some potential confusions, I mean it in an informal way of saying that spatiotemporal lattice planner applies Hybrid A*, Since time and velocity dimensions are dicretized, a state with a lower cost dominates others in the same cell even if they are not exactly the same states.
